# Generated by Django 5.2 on 2025-06-30 12:19

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('CSE', 'CSE'), ('ME', 'ME'), ('MI', 'MI'), ('CE', 'CE'), ('Math', 'Math'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload JPG or PNG image', null=True, upload_to='book_covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), books.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload a PDF file', null=True, upload_to='book_pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), books.models.validate_pdf_size]),
        ),
    ]
