# Generated by Django 5.2 on 2025-04-23 14:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='academic_session',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval required before login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='library_card',
            field=models.CharField(blank=True, default=accounts.models.generate_library_id, help_text='Auto-generated unique library card ID', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="Student's profile image", null=True, upload_to='profile_pics/'),
        ),
    ]
