# Generated by Django 5.2 on 2025-04-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_academic_session_customuser_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_librarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
