# Generated by Django 5.2 on 2025-04-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_librarian_customuser_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_librarian',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('librarian', 'Librarian')], default='student', max_length=10),
        ),
    ]
