# Generated by Django 5.2 on 2025-04-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pendingstudent_pendingteacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingStudent',
        ),
        migrations.DeleteModel(
            name='PendingTeacher',
        ),
    ]
